-- 背景图素材库表结构（背景弹框分类数据来源）
CREATE TABLE IF NOT EXISTS background_asset (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(64) NOT NULL,
  category VARCHAR(64) NOT NULL,
  category_title VARCHAR(64) NOT NULL,
  thumb_url VARCHAR(1024) NOT NULL,
  image_url VARCHAR(1024) NOT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  is_public TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  INDEX idx_background_category (category),
  INDEX idx_background_public (is_public)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 静态种子数据：图片文件放在前端 public/backgrounds/ 目录，数据库只存 URL。
-- 后续拿到高定页面整理后的真实素材时，只需替换 image_url/thumb_url 或更新图片文件。
INSERT INTO background_asset (name, category, category_title, thumb_url, image_url, sort_order) VALUES
  ('纯白', 'solid', '纯色', '/backgrounds/solid-white.svg', '/backgrounds/solid-white.svg', 1),
  ('深夜', 'solid', '纯色', '/backgrounds/solid-night.svg', '/backgrounds/solid-night.svg', 2),
  ('晴空蓝', 'solid', '纯色', '/backgrounds/solid-blue.svg', '/backgrounds/solid-blue.svg', 3),
  ('薄荷绿', 'solid', '纯色', '/backgrounds/solid-green.svg', '/backgrounds/solid-green.svg', 4),
  ('活力橙', 'solid', '纯色', '/backgrounds/solid-orange.svg', '/backgrounds/solid-orange.svg', 5),
  ('樱花粉', 'solid', '纯色', '/backgrounds/solid-pink.svg', '/backgrounds/solid-pink.svg', 6),
  ('落日', 'gradient', '渐变', '/backgrounds/grad-sunset.svg', '/backgrounds/grad-sunset.svg', 7),
  ('海洋', 'gradient', '渐变', '/backgrounds/grad-ocean.svg', '/backgrounds/grad-ocean.svg', 8),
  ('紫罗兰', 'gradient', '渐变', '/backgrounds/grad-violet.svg', '/backgrounds/grad-violet.svg', 9),
  ('薄荷', 'gradient', '渐变', '/backgrounds/grad-mint.svg', '/backgrounds/grad-mint.svg', 10),
  ('玫瑰', 'gradient', '渐变', '/backgrounds/grad-rose.svg', '/backgrounds/grad-rose.svg', 11),
  ('琥珀', 'gradient', '渐变', '/backgrounds/grad-amber.svg', '/backgrounds/grad-amber.svg', 12),
  ('波点', 'geometric', '几何', '/backgrounds/geo-dots.svg', '/backgrounds/geo-dots.svg', 13),
  ('斜纹', 'geometric', '几何', '/backgrounds/geo-stripes.svg', '/backgrounds/geo-stripes.svg', 14),
  ('波浪', 'geometric', '几何', '/backgrounds/geo-wave.svg', '/backgrounds/geo-wave.svg', 15),
  ('马赛克', 'geometric', '几何', '/backgrounds/geo-mosaic.svg', '/backgrounds/geo-mosaic.svg', 16),
  ('网格', 'geometric', '几何', '/backgrounds/geo-grid.svg', '/backgrounds/geo-grid.svg', 17),
  ('同心圆', 'geometric', '几何', '/backgrounds/geo-circle.svg', '/backgrounds/geo-circle.svg', 18),
  ('烟花', 'festival', '节日', '/backgrounds/fest-firework.svg', '/backgrounds/fest-firework.svg', 19),
  ('新春', 'festival', '节日', '/backgrounds/fest-spring.svg', '/backgrounds/fest-spring.svg', 20),
  ('生日', 'festival', '节日', '/backgrounds/fest-cake.svg', '/backgrounds/fest-cake.svg', 21),
  ('雪花', 'festival', '节日', '/backgrounds/fest-snow.svg', '/backgrounds/fest-snow.svg', 22),
  ('星愿', 'festival', '节日', '/backgrounds/fest-star.svg', '/backgrounds/fest-star.svg', 23),
  ('灯笼', 'festival', '节日', '/backgrounds/fest-lantern.svg', '/backgrounds/fest-lantern.svg', 24),
  ('科技蓝', 'business', '商务', '/backgrounds/biz-blue.svg', '/backgrounds/biz-blue.svg', 25),
  ('数据', 'business', '商务', '/backgrounds/biz-graph.svg', '/backgrounds/biz-graph.svg', 26),
  ('线条', 'business', '商务', '/backgrounds/biz-line.svg', '/backgrounds/biz-line.svg', 27),
  ('沉稳', 'business', '商务', '/backgrounds/biz-dark.svg', '/backgrounds/biz-dark.svg', 28),
  ('浅灰', 'business', '商务', '/backgrounds/biz-gray.svg', '/backgrounds/biz-gray.svg', 29),
  ('商务绿', 'business', '商务', '/backgrounds/biz-green.svg', '/backgrounds/biz-green.svg', 30),
  ('叶片', 'nature', '自然', '/backgrounds/nat-leaf.svg', '/backgrounds/nat-leaf.svg', 31),
  ('天空', 'nature', '自然', '/backgrounds/nat-sky.svg', '/backgrounds/nat-sky.svg', 32),
  ('沙滩', 'nature', '自然', '/backgrounds/nat-sand.svg', '/backgrounds/nat-sand.svg', 33),
  ('森林', 'nature', '自然', '/backgrounds/nat-forest.svg', '/backgrounds/nat-forest.svg', 34),
  ('花田', 'nature', '自然', '/backgrounds/nat-flower.svg', '/backgrounds/nat-flower.svg', 35),
  ('远山', 'nature', '自然', '/backgrounds/nat-mountain.svg', '/backgrounds/nat-mountain.svg', 36);
